In [1]:
import pandas as pd

In [2]:
master_path = '/local/data/jchen/physionet.org/files/mimic-iv-ed-full-jul21-nohup/'

In [4]:
df = pd.read_csv(master_path + 'master_dataset_multimodal_final_jul21.csv')

In [5]:
df.head(10)

,dicom_id,subject_id_x,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,...,note_seq_x,charttime_x,storetime_x,text_x,note_id_y,note_type_y,note_seq_y,charttime_y,storetime_y,text_y
0,c2a3cbe8-ad80fc7b-9696e471-e41fb7a7-b0a2d9d9,17195991,55012421,CHEST (PORTABLE AP),AP,3056,2544,21100111,220111.359,CHEST (PORTABLE AP),...,23.0,2110-01-13 09:16:00,2110-01-13 11:41:00,SINGLE FRONTAL VIEW OF THE CHEST\n\nREASON FOR...,17195991-DS-3,DS,3.0,2110-01-18 00:00:00,2110-01-18 10:47:00,\nName: ___ Unit No: ___\n...
1,06980cc1-94b37c18-8297f246-90ffe664-bc51fd35,17195991,56500894,CHEST (PORTABLE AP),AP,3056,2544,21100113,92700.921,CHEST (PORTABLE AP),...,21.0,2110-01-13 04:48:00,2110-01-13 06:33:00,EXAMINATION: CT HEAD W/O CONTRAST Q111 CT HEA...,NaN,NaN,NaN,NaN,NaN,NaN
2,75d7e206-02c947f4-fbb2eb52-ac30500b-bda33bf3,19558713,54821803,CHEST (PA AND LAT),LATERAL,3056,2544,21100115,143845.406,CHEST (PA AND LAT),...,16.0,2110-01-15 14:44:00,2110-01-15 14:56:00,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...,NaN,NaN,NaN,NaN,NaN,NaN
3,03eb85f3-96d85327-e813c974-21a4c789-0ee83971,19558713,54821803,CHEST (PA AND LAT),PA,3056,2544,21100115,143845.406,CHEST (PA AND LAT),...,16.0,2110-01-15 14:44:00,2110-01-15 14:56:00,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...,NaN,NaN,NaN,NaN,NaN,NaN
4,012cc3e1-125d54a9-f588f95f-cc464ee0-6221b5fb,12472021,57188185,CHEST (PA AND LAT),NaN,2140,1760,21100125,150703.000,CHEST (PA AND LAT),...,8.0,2110-01-25 11:35:00,2110-01-25 12:59:00,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...,14977654-DS-10,DS,10.0,2110-01-28 00:00:00,2110-01-31 22:09:00,\nName: ___ Unit No: ___\n ...
5,e381d425-3a109fec-136b3e78-d2e9a23c-993dfe81,12472021,57188185,CHEST (PA AND LAT),NaN,2140,1760,21100125,150703.000,CHEST (PA AND LAT),...,8.0,2110-01-25 11:35:00,2110-01-25 12:59:00,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...,14977654-DS-10,DS,10.0,2110-01-28 00:00:00,2110-01-31 22:09:00,\nName: ___ Unit No: ___\n ...
6,c634aa41-1709f8d3-d8db1c04-1241dbf1-7f41fe39,12426170,50633975,CHEST (PA AND LAT),LATERAL,3056,2544,21100127,192228.671,CHEST (PA AND LAT),...,4.0,2110-01-27 19:37:00,2110-01-27 23:03:00,INDICATION: ___ with recent fall on R. with ...,12426170-DS-10,DS,10.0,2110-02-01 00:00:00,2110-02-01 16:35:00,\nName: ___ Unit No: ___\...
7,c1471c1c-389f6f29-4e4fb33a-ce0e07de-a91a71d3,12426170,50633975,CHEST (PA AND LAT),LATERAL,3056,2544,21100127,192228.671,CHEST (PA AND LAT),...,4.0,2110-01-27 19:37:00,2110-01-27 23:03:00,INDICATION: ___ with recent fall on R. with ...,12426170-DS-10,DS,10.0,2110-02-01 00:00:00,2110-02-01 16:35:00,\nName: ___ Unit No: ___\...
8,56e92b0e-a9ea2e58-ac0f9d6a-75a33abf-132792cb,12426170,50633975,CHEST (PA AND LAT),AP,3056,2544,21100127,192228.671,CHEST (PA AND LAT),...,4.0,2110-01-27 19:37:00,2110-01-27 23:03:00,INDICATION: ___ with recent fall on R. with ...,12426170-DS-10,DS,10.0,2110-02-01 00:00:00,2110-02-01 16:35:00,\nName: ___ Unit No: ___\...
9,ed2ed142-a9bbf821-74ad8754-a3d9bad2-47ec4069,18970562,59049518,CHEST (PORTABLE AP),AP,2544,3056,21100201,54732.546,CHEST (PORTABLE AP),...,11.0,2110-02-01 05:47:00,2110-02-01 08:23:00,INDICATION: ___ male with alcohol intoxicatio...,18970562-DS-19,DS,19.0,2110-02-04 00:00:00,2110-02-05 07:54:00,\nName: ___ Unit No: __...

In [6]:
df.columns

Index(['dicom_id', 'subject_id_x', 'study_id',
       'PerformedProcedureStepDescription', 'ViewPosition', 'Rows', 'Columns',
       'StudyDate', 'StudyTime', 'ProcedureCodeSequence_CodeMeaning',
       ...
       'note_seq_x', 'charttime_x', 'storetime_x', 'text_x', 'note_id_y',
       'note_type_y', 'note_seq_y', 'charttime_y', 'storetime_y', 'text_y'],
      dtype='object', length=146)

In [8]:
original_path = '/local/data/jchen/physionet.org/files/mimic-iv-ed-joined/'

In [14]:
df0 = pd.read_csv(original_path + 'master_dataset-asta.csv', index_col = False)

In [10]:
len(df)

341399

In [11]:
len(df0)

425087

In [60]:
len(df0['subject_id'].unique())

205504

In [15]:
df0.columns

Index(['index', 'subject_id', 'hadm_id', 'stay_id', 'intime', 'outtime',
       'gender', 'race', 'arrival_transport', 'disposition',
       ...
       'eci_Depression', 'ed_temperature_last', 'ed_heartrate_last',
       'ed_resprate_last', 'ed_o2sat_last', 'ed_sbp_last', 'ed_dbp_last',
       'ed_pain_last', 'n_med', 'n_medrecon'],
      dtype='object', length=120)

In [17]:
df

,dicom_id,subject_id_x,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,...,note_seq_x,charttime_x,storetime_x,text_x,note_id_y,note_type_y,note_seq_y,charttime_y,storetime_y,text_y
0,c2a3cbe8-ad80fc7b-9696e471-e41fb7a7-b0a2d9d9,17195991,55012421,CHEST (PORTABLE AP),AP,3056,2544,21100111,220111.359,CHEST (PORTABLE AP),...,23.0,2110-01-13 09:16:00,2110-01-13 11:41:00,SINGLE FRONTAL VIEW OF THE CHEST\n\nREASON FOR...,17195991-DS-3,DS,3.0,2110-01-18 00:00:00,2110-01-18 10:47:00,\nName: ___ Unit No: ___\n...
1,06980cc1-94b37c18-8297f246-90ffe664-bc51fd35,17195991,56500894,CHEST (PORTABLE AP),AP,3056,2544,21100113,92700.921,CHEST (PORTABLE AP),...,21.0,2110-01-13 04:48:00,2110-01-13 06:33:00,EXAMINATION: CT HEAD W/O CONTRAST Q111 CT HEA...,NaN,NaN,NaN,NaN,NaN,NaN
2,75d7e206-02c947f4-fbb2eb52-ac30500b-bda33bf3,19558713,54821803,CHEST (PA AND LAT),LATERAL,3056,2544,21100115,143845.406,CHEST (PA AND LAT),...,16.0,2110-01-15 14:44:00,2110-01-15 14:56:00,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...,NaN,NaN,NaN,NaN,NaN,NaN
3,03eb85f3-96d85327-e813c974-21a4c789-0ee83971,19558713,54821803,CHEST (PA AND LAT),PA,3056,2544,21100115,143845.406,CHEST (PA AND LAT),...,16.0,2110-01-15 14:44:00,2110-01-15 14:56:00,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...,NaN,NaN,NaN,NaN,NaN,NaN
4,012cc3e1-125d54a9-f588f95f-cc464ee0-6221b5fb,12472021,57188185,CHEST (PA AND LAT),NaN,2140,1760,21100125,150703.000,CHEST (PA AND LAT),...,8.0,2110-01-25 11:35:00,2110-01-25 12:59:00,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...,14977654-DS-10,DS,10.0,2110-01-28 00:00:00,2110-01-31 22:09:00,\nName: ___ Unit No: ___\n ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341394,c50c2af4-8bdda7b7-32812314-f66974e8-a54e3739,16573705,50668178,CHEST (PA AND LAT),LATERAL,3056,2544,22081112,162710.500,CHEST (PA AND LAT),...,308.0,2208-11-12 16:30:00,2208-11-12 17:39:00,EXAMINATION: Chest radiograph.\n\nINDICATION:...,16573705-DS-42,DS,42.0,2208-11-15 00:00:00,2208-11-18 21:01:00,\nName: ___ Unit No: __...
341395,1ad0b826-7ee40102-15f7c784-409bb813-19d984e8,16573705,50668178,CHEST (PA AND LAT),LATERAL,3056,2544,22081112,162710.500,CHEST (PA AND LAT),...,308.0,2208-11-12 16:30:00,2208-11-12 17:39:00,EXAMINATION: Chest radiograph.\n\nINDICATION:...,16573705-DS-42,DS,42.0,2208-11-15 00:00:00,2208-11-18 21:01:00,\nName: ___ Unit No: __...
341396,79543d28-5ccda488-59d0b120-614445f4-c91a0249,13774741,58645858,CHEST (PA AND LAT),PA,3056,2544,22081115,171526.656,CHEST (PA AND LAT),...,35.0,2200-05-05 15:48:00,2200-05-05 17:48:00,"RIGHT FINGER, ___\n\nCLINICAL INFORMATION: Fo...",NaN,NaN,NaN,NaN,NaN,NaN
341397,4c9017e9-27497504-93954496-4f5d3160-8c74aa64,13774741,58645858,CHEST (PA AND LAT),LATERAL,3056,2544,22081115,171526.656,CHEST (PA AND LAT),...,35.0,2200-05-05 15:48:00,2200-05-05 17:48:00,"RIGHT FINGER, ___\n\nCLINICAL INFORMATION: Fo...",NaN,NaN,NaN,NaN,NaN,NaN
341398,775bbc9e-cf862484-0fa16a37-9d64d833-b5fe37f9,12227888,57750590,CHEST (PORTABLE AP),AP,3056,2544,22081208,120453.937,CHEST (PORTABLE AP),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_discharge = pd.read_csv('/local/data/jchen/physionet.org/files/extracted_csvs/discharge.csv')

## join with radiology notes 
df_radiology = pd.read_csv('/local/data/jchen/physionet.org/files/extracted_csvs/radiology.csv')

In [21]:
merge_discharge = pd.merge(df0, df_discharge, on=['subject_id', 'hadm_id'], how='left')

In [22]:
merge_discharge.columns

Index(['index', 'subject_id', 'hadm_id', 'stay_id', 'intime', 'outtime',
       'gender', 'race', 'arrival_transport', 'disposition',
       ...
       'ed_dbp_last', 'ed_pain_last', 'n_med', 'n_medrecon', 'note_id',
       'note_type', 'note_seq', 'charttime', 'storetime', 'text'],
      dtype='object', length=126)

In [24]:
merge_discharge['subject_id']

0         10000032
1         10000032
2         10000032
3         10000032
4         10000032
            ...
425082    19999784
425083    19999828
425084    19999828
425085    19999914
425086    19999987
Name: subject_id, Length: 425087, dtype: int64

In [25]:
merge_radiology = pd.merge(df0, df_radiology, on=['subject_id', 'hadm_id'], how='left')

In [26]:
merge_radiology.columns

Index(['index', 'subject_id', 'hadm_id', 'stay_id', 'intime', 'outtime',
       'gender', 'race', 'arrival_transport', 'disposition',
       ...
       'ed_dbp_last', 'ed_pain_last', 'n_med', 'n_medrecon', 'note_id',
       'note_type', 'note_seq', 'charttime', 'storetime', 'text'],
      dtype='object', length=126)

In [27]:
merge_radiology['subject_id']

0          10000032
1          10000032
2          10000032
3          10000032
4          10000032
             ...
3163610    19999987
3163611    19999987
3163612    19999987
3163613    19999987
3163614    19999987
Name: subject_id, Length: 3163615, dtype: int64

In [28]:
df_master_asta = pd.merge(merge_radiology, df_discharge, on=['subject_id', 'hadm_id'], how='left')

In [29]:
df_master_asta.columns

Index(['index', 'subject_id', 'hadm_id', 'stay_id', 'intime', 'outtime',
       'gender', 'race', 'arrival_transport', 'disposition',
       ...
       'note_seq_x', 'charttime_x', 'storetime_x', 'text_x', 'note_id_y',
       'note_type_y', 'note_seq_y', 'charttime_y', 'storetime_y', 'text_y'],
      dtype='object', length=132)

In [30]:
df_master_asta['subject_id']

0          10000032
1          10000032
2          10000032
3          10000032
4          10000032
             ...
3163610    19999987
3163611    19999987
3163612    19999987
3163613    19999987
3163614    19999987
Name: subject_id, Length: 3163615, dtype: int64

In [50]:
len(df_master_asta['subject_id'].unique())

205504

In [42]:
def merge_with_image_data(df_master, image_metadata_csv):
    image_metadata_csv['PStudyTime'] = image_metadata_csv['StudyTime'].apply(lambda x: f'{int(float(x)):06}' )
    image_metadata_csv['PStudyDateTime'] = pd.to_datetime(image_metadata_csv['StudyDate'].astype(str) + ' ' + image_metadata_csv['PStudyTime'].astype(str) ,format="%Y%m%d %H%M%S")

    df_master['intime'] = pd.to_datetime(df_master['intime'])
    df_master['outtime'] = pd.to_datetime(df_master['outtime'])
    merged_df = pd.merge_asof(
    image_metadata_csv.sort_values('PStudyDateTime'),
    df_master.sort_values('intime'),
    left_on='PStudyDateTime',
    right_on='intime',
    direction='backward'
    )

    merged_df = merged_df[(merged_df['PStudyDateTime'] >= merged_df['intime']) & (merged_df['PStudyDateTime'] <= merged_df['outtime'])]
    return merged_df

In [45]:


def merge_with_image_data(df_master, image_metadata_csv):

    image_metadata_csv['PStudyTime'] = image_metadata_csv['StudyTime'].apply(lambda x: f'{int(float(x)):06}')
    
   
    image_metadata_csv['PStudyDateTime'] = pd.to_datetime(
        image_metadata_csv['StudyDate'].astype(str) + ' ' + image_metadata_csv['PStudyTime'].astype(str),
        format="%Y%m%d %H%M%S"
    )

    df_master['intime'] = pd.to_datetime(df_master['intime'])
    df_master['outtime'] = pd.to_datetime(df_master['outtime'])

  
    merged_df_list = []

    # Iterate through each unique subject_id
    for subject_id in image_metadata_csv['subject_id'].unique():
        # Filter both DataFrames by the current subject_id
        image_subject = image_metadata_csv[image_metadata_csv['subject_id'] == subject_id]
        master_subject = df_master[df_master['subject_id'] == subject_id]

        # Perform asof merge for the current subject_id
        merged_subject_df = pd.merge_asof(
            image_subject.sort_values('PStudyDateTime'),
            master_subject.sort_values('intime'),
            left_on='PStudyDateTime',
            right_on='intime',
            direction='backward'
        )

        # Filter rows to ensure PStudyDateTime is within the range [intime, outtime]
        merged_subject_df = merged_subject_df[
            (merged_subject_df['PStudyDateTime'] >= merged_subject_df['intime']) & 
            (merged_subject_df['PStudyDateTime'] <= merged_subject_df['outtime'])
        ]

        
        merged_df_list.append(merged_subject_df)


    merged_df = pd.concat(merged_df_list, ignore_index=True)

    return merged_df

In [46]:
# merge with the image data
image_metadata_csv = pd.read_csv('/local/data/jchen/physionet.org/files/extracted_csvs/mimic-cxr-2.0.0-metadata.csv') 
df_master = merge_with_image_data(df_master_asta, image_metadata_csv)

In [47]:
image_metadata_csv

,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning,PStudyTime,PStudyDateTime
0,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,10000032,50414267,CHEST (PA AND LAT),PA,3056,2544,21800506,213014.531,CHEST (PA AND LAT),postero-anterior,Erect,213014,2180-05-06 21:30:14
1,174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962,10000032,50414267,CHEST (PA AND LAT),LATERAL,3056,2544,21800506,213014.531,CHEST (PA AND LAT),lateral,Erect,213014,2180-05-06 21:30:14
2,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,10000032,53189527,CHEST (PA AND LAT),PA,3056,2544,21800626,165500.312,CHEST (PA AND LAT),postero-anterior,Erect,165500,2180-06-26 16:55:00
3,e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c,10000032,53189527,CHEST (PA AND LAT),LATERAL,3056,2544,21800626,165500.312,CHEST (PA AND LAT),lateral,Erect,165500,2180-06-26 16:55:00
4,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,10000032,53911762,CHEST (PORTABLE AP),AP,2705,2539,21800723,80556.875,CHEST (PORTABLE AP),antero-posterior,NaN,080556,2180-07-23 08:05:56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377105,428e2c18-5721d8f3-35a05001-36f3d080-9053b83c,19999733,57132437,CHEST (PA AND LAT),PA,3056,2544,21520708,224550.171,CHEST (PA AND LAT),postero-anterior,Erect,224550,2152-07-08 22:45:50
377106,58c403aa-35ff8bd9-73e39f54-8dc9cc5d-e0ec3fa9,19999733,57132437,CHEST (PA AND LAT),LATERAL,3056,2544,21520708,224550.171,CHEST (PA AND LAT),lateral,Erect,224550,2152-07-08 22:45:50
377107,58766883-376a15ce-3b323a28-6af950a0-16b793bd,19999987,55368167,CHEST (PORTABLE AP),AP,2544,3056,21451104,51448.218,CHEST (PORTABLE AP),antero-posterior,Erect,051448,2145-11-04 05:14:48
377108,7ba273af-3d290f8d-e28d0ab4-484b7a86-7fc12b08,19999987,58621812,CHEST (PORTABLE AP),AP,3056,2544,21451102,202809.234,CHEST (PORTABLE AP),antero-posterior,Erect,202809,2145-11-02 20:28:09
377109,1a1fe7e3-cbac5d93-b339aeda-86bb86b5-4f31e82e,19999987,58971208,CHEST (PORTABLE AP),AP,3056,2544,21451103,50507.625,CHEST (PORTABLE AP),antero-posterior,Recumbent,050507,2145-11-03 05:05:07

In [59]:
len(image_metadata_csv['subject_id'].unique())

65379

In [51]:
df_master.columns

Index(['dicom_id', 'subject_id_x', 'study_id',
       'PerformedProcedureStepDescription', 'ViewPosition', 'Rows', 'Columns',
       'StudyDate', 'StudyTime', 'ProcedureCodeSequence_CodeMeaning',
       ...
       'note_seq_x', 'charttime_x', 'storetime_x', 'text_x', 'note_id_y',
       'note_type_y', 'note_seq_y', 'charttime_y', 'storetime_y', 'text_y'],
      dtype='object', length=146)

In [52]:
df_master[['subject_id_x', 'subject_id_y']]

        subject_id_x  subject_id_y
0           10000032    10000032.0
1           10000032    10000032.0
2           10000032    10000032.0
3           10000032    10000032.0
4           10000032    10000032.0
...              ...           ...
161486      19999376    19999376.0
161487      19999733    19999733.0
161488      19999733    19999733.0
161489      19999733    19999733.0
161490      19999987    19999987.0

[161491 rows x 2 columns]

In [54]:
df_master[df_master['subject_id_x']!=df_master['subject_id_y']]

Empty DataFrame
Columns: [dicom_id, subject_id_x, study_id, PerformedProcedureStepDescription, ViewPosition, Rows, Columns, StudyDate, StudyTime, ProcedureCodeSequence_CodeMeaning, ViewCodeSequence_CodeMeaning, PatientOrientationCodeSequence_CodeMeaning, PStudyTime, PStudyDateTime, index, subject_id_y, hadm_id, stay_id, intime, outtime, gender, race, arrival_transport, disposition, anchor_age, anchor_year, dod, admittime, dischtime, deathtime, ethnicity, edregtime, edouttime, insurance, in_year, age, outcome_inhospital_mortality, ed_los, intime_icu, time_to_icu_transfer, outcome_icu_transfer_12h, outcome_hospitalization, outcome_critical, n_ed_30d, n_ed_90d, n_ed_365d, next_ed_visit_time, next_ed_visit_time_diff, outcome_ed_revisit_3d, n_hosp_30d, n_hosp_90d, n_hosp_365d, n_icu_30d, n_icu_90d, n_icu_365d, ed_los_hours, time_to_icu_transfer_hours, next_ed_visit_time_diff_days, triage_temperature, triage_heartrate, triage_resprate, triage_o2sat, triage_sbp, triage_dbp, triage_pain, triage_acuity, chiefcomplaint, chiefcom_chest_pain, chiefcom_abdominal_pain, chiefcom_headache, chiefcom_shortness_of_breath, chiefcom_back_pain, chiefcom_cough, chiefcom_nausea_vomiting, chiefcom_fever_chills, chiefcom_syncope, chiefcom_dizziness, cci_MI, cci_CHF, cci_PVD, cci_Stroke, cci_Dementia, cci_Pulmonary, cci_Rheumatic, cci_PUD, cci_Liver1, cci_DM1, cci_DM2, cci_Paralysis, cci_Renal, cci_Cancer1, cci_Liver2, cci_Cancer2, cci_HIV, eci_CHF, eci_Arrhythmia, eci_Valvular, eci_PHTN, eci_PVD, eci_HTN1, ...]
Index: []

[0 rows x 146 columns]

In [56]:
len(df_master['subject_id_x'].unique())

47534

In [57]:
len(df_master['subject_id_y'].unique())

47534